//
//  Chart.swift
//  Kana Torii
//
//  Created by clément floret on 25/06/2020.
//  Copyright © 2020 Clément FLORET. All rights reserved.
//

import Foundation

struct Chart {
    var label: String = ""
    var labelromaji: String = ""
    
    enum collectionName: String {
        case gojuon = "Gojuon"
        case handakuon = "Dakuon & Handakuon"
        case yoon = "Yoon"
    }
    
    static let chartHiraganaGojuon = [
        Chart(label: "-a", labelromaji: " "),
        Chart(label: "-i", labelromaji: " "),
        Chart(label: "-u", labelromaji: " "),
        Chart(label: "-e", labelromaji: " "),
        Chart(label: "-o", labelromaji: " "),
        Chart(label: "あ", labelromaji: "a"),
        Chart(label: "い", labelromaji: "i"),
        Chart(label: "う", labelromaji: "u"),
        Chart(label: "え", labelromaji: "e"),
        Chart(label: "お", labelromaji: "o"),
        Chart(label: "か", labelromaji: "ka"),
        Chart(label: "き", labelromaji: "ki"),
        Chart(label: "く", labelromaji: "ku"),
        Chart(label: "け", labelromaji: "ke"),
        Chart(label: "こ", labelromaji: "ko"),
        Chart(label: "さ", labelromaji: "sa"),
        Chart(label: "し", labelromaji: "shi"),
        Chart(label: "す", labelromaji: "su"),
        Chart(label: "せ", labelromaji: "se"),
        Chart(label: "そ", labelromaji: "so"),
        Chart(label: "た", labelromaji: "ta"),
        Chart(label: "ち", labelromaji: "chi"),
        Chart(label: "つ", labelromaji: "tsu"),
        Chart(label: "て", labelromaji: "te"),
        Chart(label: "と", labelromaji: "to"),
        Chart(label: "な", labelromaji: "na"),
        Chart(label: "に", labelromaji: "ni"),
        Chart(label: "ぬ", labelromaji: "nu"),
        Chart(label: "ね", labelromaji: "ne"),
        Chart(label: "の", labelromaji: "no"),
        Chart(label: "は", labelromaji: "ha"),
        Chart(label: "ひ", labelromaji: "hi"),
        Chart(label: "ふ", labelromaji: "fu"),
        Chart(label: "へ", labelromaji: "he"),
        Chart(label: "ほ", labelromaji: "ho"),
        Chart(label: "ま", labelromaji: "ma"),
        Chart(label: "み", labelromaji: "mi"),
        Chart(label: "む", labelromaji: "mu"),
        Chart(label: "め", labelromaji: "me"),
        Chart(label: "も", labelromaji: "mo"),
        Chart(label: "や", labelromaji: "ya"),
        Chart(label: "", labelromaji: " "),
        Chart(label: "ゆ", labelromaji: "yu"),
        Chart(label: " ", labelromaji: " "),
        Chart(label: "よ", labelromaji: "yo"),
        Chart(label: "ら", labelromaji: "ra"),
        Chart(label: "り", labelromaji: "ri"),
        Chart(label: "る", labelromaji: "ru"),
        Chart(label: "れ", labelromaji: "re"),
        Chart(label: "ろ", labelromaji: "ro"),
        Chart(label: "わ", labelromaji: "wa"),
        Chart(label: " ", labelromaji: " "),
        Chart(label: " ", labelromaji: " "),
        Chart(label: " ", labelromaji: " "),
        Chart(label: "を", labelromaji: "wo"),
        Chart(label: "ん", labelromaji: "n")
    ]
    
    static let chartHiraganaDakuonHandakuon = [
        Chart(label: "-a", labelromaji: " "),
        Chart(label: "-i", labelromaji: " "),
        Chart(label: "-u", labelromaji: " "),
        Chart(label: "-e", labelromaji: " "),
        Chart(label: "-o", labelromaji: " "),
        Chart(label: "が", labelromaji: "ga"),
        Chart(label: "ぎ", labelromaji: "gi"),
        Chart(label: "ぐ", labelromaji: "gu"),
        Chart(label: "げ", labelromaji: "ge"),
        Chart(label: "ご", labelromaji: "go"),
        Chart(label: "ざ", labelromaji: "za"),
        Chart(label: "じ", labelromaji: "ji"),
        Chart(label: "ず", labelromaji: "zu"),
        Chart(label: "ぜ", labelromaji: "ze"),
        Chart(label: "ぞ", labelromaji: "zo"),
        Chart(label: "だ", labelromaji: "da"),
        Chart(label: "ぢ", labelromaji: "ji"),
        Chart(label: "づ", labelromaji: "zu"),
        Chart(label: "で", labelromaji: "de"),
        Chart(label: "ど", labelromaji: "do"),
        Chart(label: "ば", labelromaji: "ba"),
        Chart(label: "び", labelromaji: "bi"),
        Chart(label: "ぶ", labelromaji: "bu"),
        Chart(label: "べ", labelromaji: "be"),
        Chart(label: "ぼ", labelromaji: "bo"),
        Chart(label: "ぱ", labelromaji: "pa"),
        Chart(label: "ぴ", labelromaji: "pi"),
        Chart(label: "ぷ", labelromaji: "pu"),
        Chart(label: "ぺ", labelromaji: "pe"),
        Chart(label: "ぽ", labelromaji: "po")
    ]
    static let chartHiraganaYoon = [
       Chart(label: "-a", labelromaji: " "),
       Chart(label: "-u", labelromaji: " "),
       Chart(label: "-o", labelromaji: " "),
       Chart(label: "きゃ", labelromaji: "kya"),
       Chart(label: "きゅ", labelromaji: "kyu"),
       Chart(label: "きょ", labelromaji: "kyo"),
       Chart(label: "しゃ", labelromaji: "sha"),
       Chart(label: "しゅ", labelromaji: "shu"),
       Chart(label: "しょ", labelromaji: "sho"),
       Chart(label: "ちゃ", labelromaji: "cha"),
       Chart(label: "ちゅ", labelromaji: "chu"),
       Chart(label: "ちょ", labelromaji: "cho"),
       Chart(label: "にゃ", labelromaji: "nya"),
       Chart(label: "にゅ", labelromaji: "nyu"),
       Chart(label: "にょ", labelromaji: "nyo"),
       Chart(label: "ひゃ", labelromaji: "hya"),
       Chart(label: "ひゅ", labelromaji: "hyu"),
       Chart(label: "ひょ", labelromaji: "hyo"),
       Chart(label: "みゃ", labelromaji: "mya"),
       Chart(label: "みゅ", labelromaji: "myu"),
       Chart(label: "みょ", labelromaji: "myo"),
       Chart(label: "りゃ", labelromaji: "rya"),
       Chart(label: "りゅ", labelromaji: "ryu"),
       Chart(label: "りょ", labelromaji: "ryo"),
       Chart(label: "ぎゃ", labelromaji: "gya"),
       Chart(label: "ぎゅ", labelromaji: "gyu"),
       Chart(label: "ぎょ", labelromaji: "gyo"),
       Chart(label: "じゃ", labelromaji: "ja"),
       Chart(label: "じゅ", labelromaji: "ju"),
       Chart(label: "じょ", labelromaji: "jo"),
       Chart(label: "びゃ", labelromaji: "bya"),
       Chart(label: "びゅ", labelromaji: "byu"),
       Chart(label: "びょ", labelromaji: "byo"),
       Chart(label: "ぴゃ", labelromaji: "pya"),
       Chart(label: "ぴゅ", labelromaji: "pyu"),
       Chart(label: "ぴょ", labelromaji: "pyo")
    ]
    
    static let chartKatakanaGojuon = [
        Chart(label: "-a", labelromaji: " "),
        Chart(label: "-i", labelromaji: " "),
        Chart(label: "-u", labelromaji: " "),
        Chart(label: "-e", labelromaji: " "),
        Chart(label: "-o", labelromaji: " "),
        Chart(label: "ア", labelromaji: "a"),
        Chart(label: "イ", labelromaji: "i"),
        Chart(label: "ウ", labelromaji: "u"),
        Chart(label: "エ", labelromaji: "e"),
        Chart(label: "オ", labelromaji: "o"),
        Chart(label: "カ", labelromaji: "ka"),
        Chart(label: "キ", labelromaji: "ki"),
        Chart(label: "ク", labelromaji: "ku"),
        Chart(label: "ケ", labelromaji: "ke"),
        Chart(label: "コ", labelromaji: "ko"),
        Chart(label: "サ", labelromaji: "sa"),
        Chart(label: "シ", labelromaji: "shi"),
        Chart(label: "ス", labelromaji: "su"),
        Chart(label: "セ", labelromaji: "se"),
        Chart(label: "ソ", labelromaji: "so"),
        Chart(label: "タ", labelromaji: "ta"),
        Chart(label: "チ", labelromaji: "chi"),
        Chart(label: "ツ", labelromaji: "tsu"),
        Chart(label: "テ", labelromaji: "te"),
        Chart(label: "ト", labelromaji: "to"),
        Chart(label: "ナ", labelromaji: "na"),
        Chart(label: "ニ", labelromaji: "ni"),
        Chart(label: "ヌ", labelromaji: "nu"),
        Chart(label: "ネ", labelromaji: "ne"),
        Chart(label: "ノ", labelromaji: "no"),
        Chart(label: "ハ", labelromaji: "ha"),
        Chart(label: "ヒ", labelromaji: "hi"),
        Chart(label: "フ", labelromaji: "fu"),
        Chart(label: "ヘ", labelromaji: "he"),
        Chart(label: "ホ", labelromaji: "ho"),
        Chart(label: "マ", labelromaji: "ma"),
        Chart(label: "ミ", labelromaji: "mi"),
        Chart(label: "ム", labelromaji: "mu"),
        Chart(label: "メ", labelromaji: "me"),
        Chart(label: "モ", labelromaji: "mo"),
        Chart(label: "ヤ", labelromaji: "ya"),
        Chart(label: "", labelromaji: ""),
        Chart(label: "ユ", labelromaji: "yu"),
        Chart(label: " ", labelromaji: " "),
        Chart(label: "ヨ", labelromaji: "yo"),
        Chart(label: "ラ", labelromaji: "ra"),
        Chart(label: "リ", labelromaji: "ri"),
        Chart(label: "ル", labelromaji: "ru"),
        Chart(label: "レ", labelromaji: "re"),
        Chart(label: "ロ", labelromaji: "ro"),
        Chart(label: "ワ", labelromaji: "wa"),
        Chart(label: " ", labelromaji: " "),
        Chart(label: " ", labelromaji: " "),
        Chart(label: " ", labelromaji: " "),
        Chart(label: "ヲ", labelromaji: "wo"),
        Chart(label: "ン", labelromaji: "n")
    ]
    
    static let chartKatakanaDakuonHandakuon = [
        Chart(label: "-a", labelromaji: " "),
        Chart(label: "-i", labelromaji: " "),
        Chart(label: "-u", labelromaji: " "),
        Chart(label: "-e", labelromaji: " "),
        Chart(label: "-o", labelromaji: " "),
        Chart(label: "ガ", labelromaji: "ga"),
        Chart(label: "ギ", labelromaji: "gi"),
        Chart(label: "グ", labelromaji: "gu"),
        Chart(label: "ゲ", labelromaji: "ge"),
        Chart(label: "ゴ", labelromaji: "go"),
        Chart(label: "ザ", labelromaji: "za"),
        Chart(label: "ジ", labelromaji: "ji"),
        Chart(label: "ズ", labelromaji: "zu"),
        Chart(label: "ゼ", labelromaji: "ze"),
        Chart(label: "ゾ", labelromaji: "zo"),
        Chart(label: "ダ", labelromaji: "da"),
        Chart(label: "ヂ", labelromaji: "ji"),
        Chart(label: "ヅ", labelromaji: "zu"),
        Chart(label: "デ", labelromaji: "de"),
        Chart(label: "ド", labelromaji: "do"),
        Chart(label: "バ", labelromaji: "ba"),
        Chart(label: "ビ", labelromaji: "bi"),
        Chart(label: "ブ", labelromaji: "bu"),
        Chart(label: "ベ", labelromaji: "be"),
        Chart(label: "ボ", labelromaji: "bo"),
        Chart(label: "パ", labelromaji: "pa"),
        Chart(label: "ピ", labelromaji: "pi"),
        Chart(label: "プ", labelromaji: "pu"),
        Chart(label: "ペ", labelromaji: "pe"),
        Chart(label: "ポ", labelromaji: "po")
    ]
    
    static let chartKatakanaYoon = [
       Chart(label: "-a", labelromaji: " "),
       Chart(label: "-u", labelromaji: " "),
       Chart(label: "-o", labelromaji: " "),
       Chart(label: "キャ", labelromaji: "kya"),
       Chart(label: "キュ", labelromaji: "kyu"),
       Chart(label: "キョ", labelromaji: "kyo"),
       Chart(label: "シャ", labelromaji: "sha"),
       Chart(label: "シュ", labelromaji: "shu"),
       Chart(label: "ショ", labelromaji: "sho"),
       Chart(label: "チャ", labelromaji: "cha"),
       Chart(label: "チュ", labelromaji: "chu"),
       Chart(label: "チョ", labelromaji: "cho"),
       Chart(label: "ニャ", labelromaji: "nya"),
       Chart(label: "ニュ", labelromaji: "nyu"),
       Chart(label: "ニョ", labelromaji: "nyo"),
       Chart(label: "ヒャ", labelromaji: "hya"),
       Chart(label: "ヒュ", labelromaji: "hyu"),
       Chart(label: "ヒョ", labelromaji: "hyo"),
       Chart(label: "ミャ", labelromaji: "mya"),
       Chart(label: "ミュ", labelromaji: "myu"),
       Chart(label: "ミョ", labelromaji: "myo"),
       Chart(label: "リャ", labelromaji: "rya"),
       Chart(label: "リュ", labelromaji: "ryu"),
       Chart(label: "リョ", labelromaji: "ryo"),
       Chart(label: "ギャ", labelromaji: "gya"),
       Chart(label: "ギュ", labelromaji: "gyu"),
       Chart(label: "ギョ", labelromaji: "gyo"),
       Chart(label: "ジャ", labelromaji: "ja"),
       Chart(label: "ジュ", labelromaji: "ju"),
       Chart(label: "ジョ", labelromaji: "jo"),
       Chart(label: "ビャ", labelromaji: "bya"),
       Chart(label: "ビュ", labelromaji: "byu"),
       Chart(label: "ビョ", labelromaji: "byo"),
       Chart(label: "ピャ", labelromaji: "pya"),
       Chart(label: "ピュ", labelromaji: "pyu"),
       Chart(label: "ピョ", labelromaji: "pyo")
    ]
}
